language: java
install: mvn install -Dgpg.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk9
  - openjdk10
  - openjdk11
after_success:
  - mvn clean test jacoco:report coveralls:report